### PR TITLE
Remove react native. Add basic react. Serve up static react files.

### PR DESCRIPTION
**Pull request by joeylaguna**
Removed all the old react native files/folders. Added react and created a file structure to house our react files and components. Also added a babel script to compile react

### CODE REVIEW

**Comment by joeylaguna** [comment]
Added webpack and basic auth0. Can someone review this and if it looks good merge it?

**Comment by Mike26372** [comment]
Sure let me check it out

**Review by Mike26372 — COMMENTED** [review]
Any way to look at the file structure of a specific commit? Looks the config folder got deleted (twitter keys folder)

**Comment by joeylaguna** [comment]
Good catch, added it back.

**Comment by Mike26372** [comment]
Everything else looked fine to me. Not sure I have the right permissions to merge however

**Pull request merged**
